#自动激活Lean Cloud
name: AutoInsertValine

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  # schedule:
  #   - cron: "*/18 0-15 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id # 自己点的 start
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python #安装python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requests #安装requests
        run: |
          pip install requests
      - name: Waking #读取站点信息
        run: |
          python api.py
